import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import * as maplibregl from "maplibre-gl";
import Link from "next/link";
import type { Map as MapLibreMap, Marker, StyleSpecification } from "maplibre-gl";
import { confirmPlace, createComment, createPlace, isSupabaseConfigured, loadPlaces, type Category, type Comment, type Place } from "../lib/atlasRepository";

const categories: Record<Category, { label: string; icon: string; color: string }> = {
  documents: { label: "Документы", icon: "▤", color: "#7557d3" }, health: { label: "Медицина", icon: "+", color: "#dd5b67" }, food: { label: "Еда", icon: "●", color: "#e98238" }, work: { label: "Работа", icon: "◇", color: "#307cad" }, family: { label: "Для семьи", icon: "♥", color: "#d95b9b" }, leisure: { label: "Досуг", icon: "★", color: "#3d9367" },
};
const seedPlaces: Place[] = [
  { id: "1", name: "Phuket Immigration Office", category: "documents", address: "Phuket Road, Phuket Town", description: "Иммиграционный офис: визы, продления и регистрация иностранцев.", lng: 98.3913, lat: 7.8663, verified: 18, addedBy: "Анна К.", comments: [{ id: "c1", author: "Михаил", text: "Лучше приезжать утром и заранее подготовить копии документов.", date: "12 августа" }] },
  { id: "2", name: "HOMA Coworking", category: "work", address: "Samkong, Phuket Town", description: "Коворкинг со стабильным Wi‑Fi, переговорными и зонами для звонков.", lng: 98.3837, lat: 7.9061, verified: 31, addedBy: "Илья", comments: [] },
  { id: "3", name: "Bangkok Hospital Phuket", category: "health", address: "Hongyok Utis Road", description: "Международная частная клиника. Персонал говорит по-английски.", lng: 98.3827, lat: 7.9041, verified: 12, addedBy: "София", comments: [] },
  { id: "4", name: "Naka Weekend Market", category: "food", address: "Wirat Hong Yok Road", description: "Большой вечерний рынок с тайской едой, фруктами и локальными продуктами.", lng: 98.3729, lat: 7.8807, verified: 46, addedBy: "Команда Atlas", comments: [] },
  { id: "5", name: "Karon Viewpoint", category: "leisure", address: "Karon, Mueang Phuket", description: "Смотровая площадка с видом на пляжи Ката Ной, Ката и Карон.", lng: 98.3026, lat: 7.7973, verified: 73, addedBy: "Команда Atlas", comments: [] },
  { id: "6", name: "Rawai Park", category: "family", address: "Rawai, Mueang Phuket", description: "Семейный парк с игровыми зонами и бассейном для детей.", lng: 98.3278, lat: 7.7799, verified: 9, addedBy: "Мария", comments: [] },
];
const osmStyle: StyleSpecification = { version: 8, sources: { osm: { type: "raster", tiles: ["https://tile.openstreetmap.org/{z}/{x}/{y}.png"], tileSize: 256, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap</a>', maxzoom: 19 } }, layers: [{ id: "osm", type: "raster", source: "osm" }] };
const STORAGE_KEY = "atlas-demo-phuket-v1";

export default function AtlasMap() {
  const containerRef = useRef<HTMLDivElement>(null); const mapRef = useRef<MapLibreMap | null>(null); const markersRef = useRef<Marker[]>([]);
  const [places, setPlaces] = useState<Place[]>(seedPlaces); const [selected, setSelected] = useState<Place | null>(null); const [filter, setFilter] = useState<Category | "all">("all"); const [query, setQuery] = useState(""); const [adding, setAdding] = useState(false); const [draft, setDraft] = useState<{ lng: number; lat: number } | null>(null); const [notice, setNotice] = useState("");
  const addingRef = useRef(false); addingRef.current = adding;
  useEffect(() => { if (isSupabaseConfigured) { loadPlaces().then(data => { if (data.length) setPlaces(data); }).catch(() => setNotice("Не удалось загрузить облачные данные — включён локальный режим")); } else { const raw = localStorage.getItem(STORAGE_KEY); if (raw) try { setPlaces(JSON.parse(raw)); } catch {} } }, []);
  useEffect(() => { if (!isSupabaseConfigured) localStorage.setItem(STORAGE_KEY, JSON.stringify(places)); }, [places]);
  const visible = useMemo(() => places.filter(p => (filter === "all" || p.category === filter) && `${p.name} ${p.address}`.toLowerCase().includes(query.toLowerCase())), [places, filter, query]);
  useEffect(() => { if (!containerRef.current || mapRef.current) return; const map = new maplibregl.Map({ container: containerRef.current, style: osmStyle, center: [98.365, 7.86], zoom: 10.7, attributionControl: false }); map.addControl(new maplibregl.NavigationControl({ showCompass: false }), "bottom-right"); map.addControl(new maplibregl.AttributionControl({ compact: true }), "bottom-right"); map.on("click", e => { if (addingRef.current) { setDraft({ lng: e.lngLat.lng, lat: e.lngLat.lat }); setAdding(false); } }); mapRef.current = map; return () => { map.remove(); mapRef.current = null; }; }, []);
  useEffect(() => { const map = mapRef.current; if (!map) return; markersRef.current.forEach(m => m.remove()); markersRef.current = visible.map(place => { const el = document.createElement("button"); el.className = "place-marker"; el.type = "button"; el.title = place.name; el.setAttribute("aria-label", `${categories[place.category].label}: ${place.name}`); el.style.setProperty("--marker", categories[place.category].color); el.textContent = categories[place.category].icon; el.addEventListener("click", e => { e.stopPropagation(); setSelected(place); map.flyTo({ center: [place.lng, place.lat], zoom: Math.max(map.getZoom(), 14), essential: true }); }); return new maplibregl.Marker({ element: el, anchor: "bottom" }).setLngLat([place.lng, place.lat]).addTo(map); }); }, [visible]);
  const addPlace = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!draft) return; const data = new FormData(event.currentTarget); let place: Place = { id: crypto.randomUUID(), name: String(data.get("name")), address: String(data.get("address")), description: String(data.get("description")), category: data.get("category") as Category, ...draft, verified: 0, addedBy: "Вы", comments: [] }; try { if (isSupabaseConfigured) place = await createPlace(place); setPlaces(current => [...current, place]); setDraft(null); setSelected(place); setNotice(isSupabaseConfigured ? "Место добавлено в общую карту" : "Место сохранено в этом браузере"); } catch { setNotice("Не удалось добавить место. Попробуйте ещё раз"); } };
  const addComment = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected) return; const text = String(new FormData(event.currentTarget).get("comment")).trim(); if (!text) return; let comment: Comment = { id: crypto.randomUUID(), author: "Гость", text, date: "сегодня" }; try { if (isSupabaseConfigured) comment = await createComment(selected.id, comment); const updated = { ...selected, comments: [...selected.comments, comment] }; setPlaces(current => current.map(p => p.id === updated.id ? updated : p)); setSelected(updated); event.currentTarget.reset(); setNotice("Комментарий опубликован"); } catch { setNotice("Не удалось опубликовать комментарий"); } };
  const verify = async () => { if (!selected) return; try { const count = isSupabaseConfigured ? await confirmPlace(selected.id) : selected.verified + 1; const updated = { ...selected, verified: count }; setPlaces(current => current.map(p => p.id === updated.id ? updated : p)); setSelected(updated); setNotice("Спасибо! Актуальность подтверждена"); } catch { setNotice("Не удалось подтвердить актуальность"); } };
  return <div className={`atlas ${adding ? "is-adding" : ""}`}><a className="skip-link" href="#map">Перейти к карте</a><header className="topbar"><button className="brand" type="button" onClick={() => { setSelected(null); mapRef.current?.flyTo({ center: [98.365, 7.86], zoom: 10.7 }); }}><span className="brand-mark">A</span><span>Atlas</span></button><div className="city"><span>Пхукет</span><small>Таиланд</small></div><label className="search"><span aria-hidden="true">⌕</span><span className="sr-only">Поиск мест</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Найти место или адрес" /></label><button className="primary" type="button" onClick={() => { setAdding(true); setSelected(null); setNotice("Нажмите на нужное место на карте"); }}>＋ Добавить место</button><Link className="avatar" href="/profile" aria-label="Открыть профиль администратора">Г</Link></header>
  <nav className="filters" aria-label="Категории"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>Все места <span>{places.length}</span></button>{(Object.keys(categories) as Category[]).map(key => <button key={key} className={filter === key ? "active" : ""} onClick={() => setFilter(key)}><i style={{ background: categories[key].color }}>{categories[key].icon}</i>{categories[key].label}</button>)}</nav><main id="map" ref={containerRef} className="map" aria-label="Интерактивная карта Пхукета" /><div className="result-count" role="status">Найдено мест: {visible.length}</div>{notice && <div className="toast" role="status"><span>{notice}</span><button type="button" aria-label="Закрыть уведомление" onClick={() => setNotice("")}>×</button></div>}
  {selected && <aside className="place-card" aria-label={`Информация о ${selected.name}`}><button className="close" type="button" aria-label="Закрыть карточку" onClick={() => setSelected(null)}>×</button><div className="place-hero" style={{ background: categories[selected.category].color }}><span>{categories[selected.category].icon}</span><small>{categories[selected.category].label}</small></div><div className="place-body"><p className="verified">✓ Подтверждено сообществом · {selected.verified}</p><h2>{selected.name}</h2><p className="address">⌖ {selected.address}</p><p className="description">{selected.description}</p><p className="byline">Добавил: {selected.addedBy}</p><div className="card-actions"><button type="button" onClick={verify}>✓ Информация актуальна</button><a href={`https://www.openstreetmap.org/directions?to=${selected.lat},${selected.lng}`} target="_blank" rel="noreferrer">Маршрут ↗</a></div><section className="comments"><h3>Комментарии <span>{selected.comments.length}</span></h3>{selected.comments.map(c => <article key={c.id}><strong>{c.author}</strong><time>{c.date}</time><p>{c.text}</p></article>)}{!selected.comments.length && <p className="empty">Пока нет комментариев. Поделитесь опытом первым.</p>}<form onSubmit={addComment}><label htmlFor="comment">Ваш комментарий</label><textarea id="comment" name="comment" required placeholder="Что важно знать об этом месте?" /><button className="primary" type="submit">Опубликовать</button></form></section></div></aside>}
  {draft && <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) setDraft(null); }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="add-title"><button className="close" type="button" aria-label="Закрыть" onClick={() => setDraft(null)}>×</button><p className="eyebrow">Новая метка</p><h2 id="add-title">Добавить место</h2><p>Расскажите сообществу, чем полезно это место.</p><form onSubmit={addPlace}><label>Название<input name="name" required autoFocus /></label><label>Категория<select name="category">{(Object.keys(categories) as Category[]).map(key => <option key={key} value={key}>{categories[key].label}</option>)}</select></label><label>Адрес<input name="address" required /></label><label>Описание<textarea name="description" required /></label><div className="modal-actions"><button type="button" onClick={() => setDraft(null)}>Отмена</button><button className="primary" type="submit">Добавить на карту</button></div></form></section></div>}</div>;
}
